<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Nov 21, 2024 54835 PM_1</name>
   <tag></tag>
   <elementGuidId>9733ce7a-72cf-46aa-bb78-6c62914af83c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#anchor1 > td.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='anchor1']/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>1ad261a6-fe43-4f94-a3d2-15e4c51ef337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>9c90bb1f-84fc-4d44-92b9-db46f840a614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nov 21, 2024 5:48:35 PM</value>
      <webElementGuid>868c990c-d686-4cce-a60b-1a48685e7b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;anchor1&quot;)/td[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>e8aaefef-2bf9-42ae-a546-88490acc9a88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='anchor1']/td</value>
      <webElementGuid>6e1bff47-044b-4bb9-840e-e843b9439e1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Debit'])[1]/following::td[1]</value>
      <webElementGuid>ac997863-2c58-4b5a-a948-de35e9810779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nov 21, 2024 5:48:45 PM'])[1]/following::td[3]</value>
      <webElementGuid>06c15134-18c4-409c-aefa-0f5a0ecc35d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit'])[1]/preceding::td[2]</value>
      <webElementGuid>8adf4569-2564-4f3b-b7c4-96c207279cb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;'])[1]/preceding::td[3]</value>
      <webElementGuid>d27f6c7e-2281-47f5-84c3-6f493adffb9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nov 21, 2024 5:48:35 PM']/parent::*</value>
      <webElementGuid>71aa43b0-9140-4f0b-8f5b-73d22556d7cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td</value>
      <webElementGuid>274e1fd4-2702-4206-af1b-7f95fa60df98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Nov 21, 2024 5:48:35 PM' or . = 'Nov 21, 2024 5:48:35 PM')]</value>
      <webElementGuid>22ed0166-a485-4917-9b62-84d51e59e94e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
