<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Nov 21, 2024 54508 PM</name>
   <tag></tag>
   <elementGuidId>eb75f8b6-4b10-49af-abe8-e0c3ed2db0c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='anchor0']/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>d1075ce8-faa2-4d20-a708-621380bd1cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>927c2611-801d-4d1b-814c-1ba043309d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nov 21, 2024 5:45:08 PM</value>
      <webElementGuid>34ed6efa-60c6-432f-b394-4a085a42320d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;anchor0&quot;)/td[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>2f1f44a1-4c9f-4770-8da0-17cf1f912ba4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='anchor0']/td</value>
      <webElementGuid>e44e4dbf-733c-4900-9520-04098b475cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Type'])[1]/following::td[1]</value>
      <webElementGuid>f58f7551-5bae-43af-ab39-8b5241177215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount'])[1]/following::td[2]</value>
      <webElementGuid>16137efa-4d37-482f-833f-62476a3c5581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Debit'])[1]/preceding::td[2]</value>
      <webElementGuid>7839a034-cc8d-4967-bdf5-6dbf7f59af80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nov 21, 2024 5:45:01 PM'])[1]/preceding::td[3]</value>
      <webElementGuid>ff0aff6d-905d-4aa7-8dad-a1da585fcfb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nov 21, 2024 5:45:08 PM']/parent::*</value>
      <webElementGuid>fdfe8b17-a52f-47bb-9b47-df8b9495e30b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/td</value>
      <webElementGuid>2c1a93dd-592c-48ea-b8d6-c7969954265c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Nov 21, 2024 5:45:08 PM' or . = 'Nov 21, 2024 5:45:08 PM')]</value>
      <webElementGuid>82b4eeac-e9fd-4323-a38e-1c3b11a2ec86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
