<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Nov 21, 2024 55610 PM_1</name>
   <tag></tag>
   <elementGuidId>d740e29c-b101-42c2-8179-b15a96b460ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#anchor1 > td.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='anchor1']/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>49500004-14c0-4458-b93c-75dc325b539b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>22652b8f-1544-4e76-be72-c8a3abcf06f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nov 21, 2024 5:56:10 PM</value>
      <webElementGuid>c026be6a-27e4-4696-86ab-dfa8971b053d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;anchor1&quot;)/td[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>e5b92816-0386-4957-9994-ade5bcb7b205</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='anchor1']/td</value>
      <webElementGuid>a777be17-1a1f-409b-b906-7844cab801fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit'])[1]/following::td[1]</value>
      <webElementGuid>976ec0e9-b410-400c-9259-7ae1dff8fbff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nov 21, 2024 5:56:00 PM'])[1]/following::td[3]</value>
      <webElementGuid>f2dd32be-0df7-4024-9307-6b5e03bf5ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Debit'])[1]/preceding::td[2]</value>
      <webElementGuid>fff94fd7-84bb-45c1-bfb2-4dc2c79f4358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;'])[1]/preceding::td[3]</value>
      <webElementGuid>3e79a769-05ef-4f2b-818d-b44b86ebc8c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nov 21, 2024 5:56:10 PM']/parent::*</value>
      <webElementGuid>df17764c-cc1a-4cdf-b232-ceb57130b337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td</value>
      <webElementGuid>e6e049e8-1a94-4dff-a343-e40cfe36797d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Nov 21, 2024 5:56:10 PM' or . = 'Nov 21, 2024 5:56:10 PM')]</value>
      <webElementGuid>a0ae3bb3-7175-43c6-8177-8943f180ea82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
