<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Nov 21, 2024 54845 PM</name>
   <tag></tag>
   <elementGuidId>e5e14587-5dea-4504-97d1-f91d70001a2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#anchor1 > td.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='anchor1']/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>db2695ec-2800-45e1-b17a-cb774196f1a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>0ed0ead5-5ed0-4651-ab12-dc61697e7aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nov 21, 2024 5:48:45 PM</value>
      <webElementGuid>d07e1d4e-6929-4f91-8e1f-168ecaca8ad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;anchor1&quot;)/td[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>5b1ad631-6d7b-482e-9597-28778386f156</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='anchor1']/td</value>
      <webElementGuid>ded59599-a75b-43a6-a3d9-3e931ba6e143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit'])[1]/following::td[1]</value>
      <webElementGuid>acf586c7-6299-449a-bec6-829e15b58687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nov 21, 2024 5:48:35 PM'])[1]/following::td[3]</value>
      <webElementGuid>d02a8d8e-6343-4c60-ac3e-227ccc5c97c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Debit'])[1]/preceding::td[2]</value>
      <webElementGuid>0f38b511-c75d-48a7-9640-43d8c6b8e90b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;'])[1]/preceding::td[3]</value>
      <webElementGuid>c38a560b-500b-4866-857c-c4f4a9a51b0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nov 21, 2024 5:48:45 PM']/parent::*</value>
      <webElementGuid>95d09b44-82fe-4b69-bf09-d35105b469a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td</value>
      <webElementGuid>4aab4c76-f250-40b2-8398-303c8d606b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Nov 21, 2024 5:48:45 PM' or . = 'Nov 21, 2024 5:48:45 PM')]</value>
      <webElementGuid>08b70515-5f57-42e6-a0a2-c1c29652106e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
